name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    environment: production
    env:
      APP_NAME: ${{secrets.APP_NAME}}
      APP_VERSION: ${{secrets.APP_VERSION}}
      DEBUG: ${{secrets.DEBUG}}
      API_V1_PREFIX: ${{secrets.API_V1_PREFIX}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      TEST_DB: ${{secrets.TEST_DB}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    services:
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}_test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling the latest changes
        uses: actions/checkout@v7
      - name: Install uv and python version 3.14
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          python-version: 3.14
          activate-environment: 'true'
      - name: Install dependencies
        run: uv sync
      - name: Run the test
        run: uv run pytest
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapitemplate:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}


  deploy:
    needs:
      - build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Pulling the latest changes
        uses: actions/checkout@v7
      - name: Deploy to ubuntu server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd app/src
            git pull
            echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart api
            
